import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { NavbarComponent, FooterComponent } from './index'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>LSP BPPTIK Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel=" icon" href="../public/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <NavbarComponent/>
        <main className={styles.main}>
          {children}
        </main>
        <FooterComponent/>
      </div>
    </>
  )
}
